[services.doctor]
address = "localhost:8081"
timeout = 15

[server]
port = 8082

[database]
type = "postgres" # supported: sqlite3, postgres

[database.sqlite3]
source = "./db/appointment.db"

[database.postgres]
host = "localhost"
port = 5432
user = "postgres"
password = "1"
db = "appointment"

[message-broker]
type = "nats" # supported: nats

[message-broker.nats]
connection_url = "message-broker-nats"