[server]
port = 8081

[database]
type = "postgres" # supported: sqlite3, postgres

[database.sqlite3]
source = "./db/doctor.db"

[database.postgres]
connection_url = "user=postgres password=1 dbname=doctor sslmode=disable"

[message-broker]
type = "nats" # supported: nats

[message-broker.nats]
connection_url = "localhost:4222"