[server]
port = 8081

[cache]
type = "redis" # supported: redis
ttl = 60

[cache.redis]
url = "redis://localhost:6379"

[database]
type = "postgres" # supported: sqlite3, postgres

[database.sqlite3]
source = "./db/doctor.db"

[database.postgres]
host = "localhost"
port = 5432
user = "postgres"
password = "1"
db = "doctor"

[message-broker]
type = "nats" # supported: nats

[message-broker.nats]
connection_url = "localhost:4222"