// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/doctor.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorRequest) Reset() {
	*x = GetDoctorRequest{}
	mi := &file_proto_doctor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorRequest) ProtoMessage() {}

func (x *GetDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctor_proto_rawDescGZIP(), []int{0}
}

func (x *GetDoctorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetDoctorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorsRequest) Reset() {
	*x = GetDoctorsRequest{}
	mi := &file_proto_doctor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorsRequest) ProtoMessage() {}

func (x *GetDoctorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorsRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctor_proto_rawDescGZIP(), []int{1}
}

type CreateDoctorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FullName       string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Specialization string                 `protobuf:"bytes,2,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDoctorRequest) Reset() {
	*x = CreateDoctorRequest{}
	mi := &file_proto_doctor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDoctorRequest) ProtoMessage() {}

func (x *CreateDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDoctorRequest.ProtoReflect.Descriptor instead.
func (*CreateDoctorRequest) Descriptor() ([]byte, []int) {
	return file_proto_doctor_proto_rawDescGZIP(), []int{2}
}

func (x *CreateDoctorRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateDoctorRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *CreateDoctorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type DoctorResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Specialization string                 `protobuf:"bytes,3,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DoctorResponse) Reset() {
	*x = DoctorResponse{}
	mi := &file_proto_doctor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorResponse) ProtoMessage() {}

func (x *DoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorResponse.ProtoReflect.Descriptor instead.
func (*DoctorResponse) Descriptor() ([]byte, []int) {
	return file_proto_doctor_proto_rawDescGZIP(), []int{3}
}

func (x *DoctorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DoctorResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *DoctorResponse) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *DoctorResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetDoctorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doctors       []*DoctorResponse      `protobuf:"bytes,1,rep,name=doctors,proto3" json:"doctors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorsResponse) Reset() {
	*x = GetDoctorsResponse{}
	mi := &file_proto_doctor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorsResponse) ProtoMessage() {}

func (x *GetDoctorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_doctor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorsResponse.ProtoReflect.Descriptor instead.
func (*GetDoctorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_doctor_proto_rawDescGZIP(), []int{4}
}

func (x *GetDoctorsResponse) GetDoctors() []*DoctorResponse {
	if x != nil {
		return x.Doctors
	}
	return nil
}

var File_proto_doctor_proto protoreflect.FileDescriptor

const file_proto_doctor_proto_rawDesc = "" +
	"\n" +
	"\x12proto/doctor.proto\x12\x06doctor\"\"\n" +
	"\x10GetDoctorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x13\n" +
	"\x11GetDoctorsRequest\"p\n" +
	"\x13CreateDoctorRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12&\n" +
	"\x0especialization\x18\x02 \x01(\tR\x0especialization\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"{\n" +
	"\x0eDoctorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12&\n" +
	"\x0especialization\x18\x03 \x01(\tR\x0especialization\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"F\n" +
	"\x12GetDoctorsResponse\x120\n" +
	"\adoctors\x18\x01 \x03(\v2\x16.doctor.DoctorResponseR\adoctors2\xd8\x01\n" +
	"\rDoctorService\x12=\n" +
	"\tGetDoctor\x12\x18.doctor.GetDoctorRequest\x1a\x16.doctor.DoctorResponse\x12C\n" +
	"\n" +
	"GetDoctors\x12\x19.doctor.GetDoctorsRequest\x1a\x1a.doctor.GetDoctorsResponse\x12C\n" +
	"\fCreateDoctor\x12\x1b.doctor.CreateDoctorRequest\x1a\x16.doctor.DoctorResponseB.Z,github.com/pythonsogood/ap-assignment1/protob\x06proto3"

var (
	file_proto_doctor_proto_rawDescOnce sync.Once
	file_proto_doctor_proto_rawDescData []byte
)

func file_proto_doctor_proto_rawDescGZIP() []byte {
	file_proto_doctor_proto_rawDescOnce.Do(func() {
		file_proto_doctor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_doctor_proto_rawDesc), len(file_proto_doctor_proto_rawDesc)))
	})
	return file_proto_doctor_proto_rawDescData
}

var file_proto_doctor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_doctor_proto_goTypes = []any{
	(*GetDoctorRequest)(nil),    // 0: doctor.GetDoctorRequest
	(*GetDoctorsRequest)(nil),   // 1: doctor.GetDoctorsRequest
	(*CreateDoctorRequest)(nil), // 2: doctor.CreateDoctorRequest
	(*DoctorResponse)(nil),      // 3: doctor.DoctorResponse
	(*GetDoctorsResponse)(nil),  // 4: doctor.GetDoctorsResponse
}
var file_proto_doctor_proto_depIdxs = []int32{
	3, // 0: doctor.GetDoctorsResponse.doctors:type_name -> doctor.DoctorResponse
	0, // 1: doctor.DoctorService.GetDoctor:input_type -> doctor.GetDoctorRequest
	1, // 2: doctor.DoctorService.GetDoctors:input_type -> doctor.GetDoctorsRequest
	2, // 3: doctor.DoctorService.CreateDoctor:input_type -> doctor.CreateDoctorRequest
	3, // 4: doctor.DoctorService.GetDoctor:output_type -> doctor.DoctorResponse
	4, // 5: doctor.DoctorService.GetDoctors:output_type -> doctor.GetDoctorsResponse
	3, // 6: doctor.DoctorService.CreateDoctor:output_type -> doctor.DoctorResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_doctor_proto_init() }
func file_proto_doctor_proto_init() {
	if File_proto_doctor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_doctor_proto_rawDesc), len(file_proto_doctor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_doctor_proto_goTypes,
		DependencyIndexes: file_proto_doctor_proto_depIdxs,
		MessageInfos:      file_proto_doctor_proto_msgTypes,
	}.Build()
	File_proto_doctor_proto = out.File
	file_proto_doctor_proto_goTypes = nil
	file_proto_doctor_proto_depIdxs = nil
}
