services:
  message-broker-nats:
    image: nats:scratch
    command: "-c /etc/nats/nats.conf"
    restart: unless-stopped
    ports:
      - "4222:4222" # client
      - "6222:6222" # cluster
      - "8222:8222" # monitor
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf
  doctor-service:
    image: doctor-service
    build:
      context: .
      dockerfile: ./doctor-service/Dockerfile
    environment:
      CONFIG_FILE: config.toml
    volumes:
      - doctor-data:/app/db
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - message-broker-nats
  appointment-service:
    image: appointment-service
    build:
      context: .
      dockerfile: ./appointment-service/Dockerfile
    environment:
      CONFIG_FILE: config.toml
    volumes:
      - appointment-data:/app/db
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      - message-broker-nats
  notification-service:
    image: notification-service
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    environment:
      CONFIG_FILE: config.toml
    restart: unless-stopped
    depends_on:
      - message-broker-nats

volumes:
  doctor-data:
    driver: local
  appointment-data:
    driver: local
