services:
  message-broker-nats:
    image: nats:alpine
    command: "-c /etc/nats/nats.conf"
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8222/healthz" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
  cache-redis:
    image: redis:8-alpine
    command: >
      sh -c '
        mkdir -p /usr/local/etc/redis &&
        echo "bind 0.0.0.0" > /usr/local/etc/redis/redis.conf &&
        echo "requirepass $CACHE_REDIS_PASSWORD" >> /usr/local/etc/redis/redis.conf &&
        echo "user default on nopass ~* +@all" > /usr/local/etc/redis/users.acl &&
        echo "user $CACHE_REDIS_USER on >$CACHE_REDIS_USER_PASSWORD ~* +@all" >> /usr/local/etc/redis/users.acl &&
        redis-server /usr/local/etc/redis/redis.conf --aclfile /usr/local/etc/redis/users.acl
      '
    volumes:
      - redis-data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "$CACHE_REDIS_PASSWORD", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  doctor-service-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DOCTOR_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCTOR_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DOCTOR_SERVICE_POSTGRES_DB}
      PGDATA : /var/lib/postgresql/docker
    volumes:
      - doctor-postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  doctor-service:
    image: doctor-service
    build:
      context: .
      dockerfile: ./doctor-service/Dockerfile
    environment:
      CONFIG_FILE: config.toml
      SERVER_RATE_LIMIT_RPM: ${DOCTOR_SERVICE_SERVER_RATE_LIMIT_RPM}
      MESSAGE_BROKER_NATS_CONNECTION_URL: ${NATS_CONNECTION_URL}
      CACHE_REDIS_URL: "redis://cache-redis:6379"
      CACHE_TTL: ${CACHE_TTL_SECONDS}
      DB_POSTGRES_HOST: "doctor-service-postgres"
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: ${DOCTOR_SERVICE_POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${DOCTOR_SERVICE_POSTGRES_PASSWORD}
      DB_POSTGRES_DB: ${DOCTOR_SERVICE_POSTGRES_DB}
    volumes:
      - doctor-data:/app/db
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      cache-redis:
        condition: service_healthy
      doctor-service-postgres:
        condition: service_healthy
      message-broker-nats:
        condition: service_healthy
  appointment-service-postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${APPOINTMENT_SERVICE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${APPOINTMENT_SERVICE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${APPOINTMENT_SERVICE_POSTGRES_DB}
      PGDATA : /var/lib/postgresql/docker
    volumes:
      - appointment-postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  appointment-service:
    image: appointment-service
    build:
      context: .
      dockerfile: ./appointment-service/Dockerfile
    environment:
      CONFIG_FILE: config.toml
      SERVER_RATE_LIMIT_RPM: ${APPOINTMENT_SERVICE_SERVER_RATE_LIMIT_RPM}
      MESSAGE_BROKER_NATS_CONNECTION_URL: ${NATS_CONNECTION_URL}
      CACHE_REDIS_URL: "redis://cache-redis:6379"
      CACHE_TTL: ${CACHE_TTL_SECONDS}
      DB_POSTGRES_HOST: "appointment-service-postgres"
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: ${APPOINTMENT_SERVICE_POSTGRES_USER}
      DB_POSTGRES_PASSWORD: ${APPOINTMENT_SERVICE_POSTGRES_PASSWORD}
      DB_POSTGRES_DB: ${APPOINTMENT_SERVICE_POSTGRES_DB}
      SERVICES_DOCTOR_ADDRESS: ${DOCTOR_SERVICE_ADDRESS}
      SERVICES_DOCTOR_TIMEOUT: ${DOCTOR_SERVICE_TIMEOUT}
    volumes:
      - appointment-data:/app/db
    ports:
      - "8082:8082"
    restart: unless-stopped
    depends_on:
      cache-redis:
        condition: service_healthy
      appointment-service-postgres:
        condition: service_healthy
      message-broker-nats:
        condition: service_healthy
  notification-service:
    image: notification-service
    build:
      context: .
      dockerfile: ./notification-service/Dockerfile
    environment:
      CONFIG_FILE: config.toml
      MESSAGE_BROKER_NATS_CONNECTION_URL: ${NATS_CONNECTION_URL}
      REDIS_URL: "redis://cache-redis:6379"
      LOG_FILE: ${NOTIFICATION_SERVICE_LOG_DIRECTORY}/${NOTIFICATION_SERVICE_LOG_FILE}
      GATEWAY_URL: "http://gateway-service:8080"
      WORKER_POOL_SIZE: ${NOTIFICATION_SERVICE_WORKER_POOL_SIZE}
    volumes:
      - notification-logs:/app/${NOTIFICATION_SERVICE_LOG_DIRECTORY}
    restart: unless-stopped
    depends_on:
      cache-redis:
        condition: service_healthy
      message-broker-nats:
        condition: service_healthy
  gateway-service:
    image: gateway-service
    build:
      context: .
      dockerfile: ./mock-gateway/Dockerfile
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
  doctor-data:
    driver: local
  doctor-postgres-data:
    driver: local
  appointment-data:
    driver: local
  appointment-postgres-data:
    driver: local
  notification-logs:
    driver: local
